const scheduleInfo = [
  {
    title: "抽選履修登録期間",
    description: "Webでの抽選履修登録",
    start: "2026-04-03",
    end: "2026-04-06",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録期間",
    description: "通常科目の履修登録（最終日は23:55まで）",
    start: "2026-04-09",
    end: "2026-04-12 23:55",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-04-13",
    end: "2026-04-16",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-04-24",
    end: "2026-04-30 23:55",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "水曜日の授業実施",
    description: "昭和の日のため水曜日の授業を実施",
    start: "2026-04-30",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "1Q 試験",
    description: "第1クウォーター試験日",
    start: "2026-06-04",
    end: "2026-06-11",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-06-12",
    end: "2026-06-18",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "臨時休業",
    description: "入学者選抜実施に伴う休業",
    start: "2026-06-19",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-06-25",
    end: "2026-07-02",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "2Q 試験",
    description: "第2クウォーター試験日",
    start: "2026-07-28",
    end: "2026-08-12",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "夏季休業期間",
    description: "夏季休暇",
    start: "2026-08-13",
    end: "2026-09-30",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "試験予備日",
    description: "非常変災等による試験延期時の予備日",
    start: "2026-08-19",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期抽選履修登録期間",
    description: "Webでの抽選履修登録",
    start: "2026-09-14",
    end: "2026-09-16",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録期間",
    description: "後期科目の履修登録",
    start: "2026-09-24",
    end: "2026-09-30",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-10-01",
    end: "2026-10-07",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-10-16",
    end: "2026-10-21",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "臨時休業・工大祭",
    description: "工大祭準備および開催に伴う休業",
    start: "2026-10-09",
    end: "2026-10-13",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "moodle停止予定日",
    description: "moodle 使用不可に備えた対応を",
    start: "2026-10-09",
    end: "2026-10-12",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "スポーツの日の振替として月曜日の授業を実施",
    start: "2026-10-15",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "3Q 試験",
    description: "第3クウォーター試験日",
    start: "2026-12-01",
    end: "2026-12-08",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-12-09",
    end: "2026-12-15",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-12-19",
    end: "2026-12-24",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "冬季休業期間",
    description: "年末年始の休み",
    start: "2026-12-26",
    end: "2027-01-03",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "成人の日の振替として月曜日の授業を実施",
    start: "2027-01-13",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "4Q 試験",
    description: "第4クウォーター試験日",
    start: "2027-01-28",
    end: "2027-02-18",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "試験予備日",
    description: "非常変災等による試験延期時の予備日",
    start: "2027-02-13",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "試験予備日",
    description: "非常変災等による試験延期時の予備日",
    start: "2027-02-19",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
];

export default scheduleInfo;
