const scheduleInfo = [
  {
    title: "抽選履修登録期間",
    description: "Webでの抽選履修登録",
    start: "2026-04-03",
    end: "2026-04-07",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録期間",
    description: "通常科目の履修登録（最終日は23:55まで）",
    start: "2026-04-09",
    end: "2026-04-12 23:55",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-04-13",
    end: "2026-04-16",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-04-24",
    end: "2026-04-30 23:55",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "昭和の日の振替として月曜日の授業を実施",
    start: "2026-04-30",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "火曜日の授業実施",
    description: "授業日数調整のため火曜日の授業を実施",
    start: "2026-05-29",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "1Q 試験",
    description: "第1クウォーター試験日",
    start: "2026-06-03",
    end: "2026-06-10",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-06-11",
    end: "2026-06-17",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "金曜日の授業実施",
    description: "授業日数調整のため金曜日の授業を実施",
    start: "2026-06-18",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "臨時休業",
    description: "入学者選抜実施に伴う休業",
    start: "2026-06-20",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "前期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-06-25",
    end: "2026-07-01",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "海の日の振替として月曜日の授業を実施",
    start: "2026-07-24",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "2Q 試験",
    description: "第2クウォーター試験日",
    start: "2026-07-25",
    end: "2026-08-12",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "夏季休業期間",
    description: "夏季休暇",
    start: "2026-08-13",
    end: "2026-09-30",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "試験予備日",
    description: "非常変災等による試験延期時の予備日",
    start: "2026-08-19",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期抽選履修登録期間",
    description: "Webでの抽選履修登録",
    start: "2026-09-12",
    end: "2026-09-17",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録期間",
    description: "後期科目の履修登録",
    start: "2026-09-24",
    end: "2026-09-30",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-10-01",
    end: "2026-10-07",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-10-16",
    end: "2026-10-21",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "臨時休業・工大祭",
    description: "工大祭準備および開催に伴う休業",
    start: "2026-10-10",
    end: "2026-10-13",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "スポーツの日の振替として月曜日の授業を実施",
    start: "2026-10-15",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "勤労感謝の日の振替として月曜日の授業を実施",
    start: "2026-11-25",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "臨時休業",
    description: "大学行事等に伴う休業",
    start: "2026-11-26",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "3Q 試験",
    description: "第3クウォーター試験日",
    start: "2026-12-01",
    end: "2026-12-08",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録修正期間",
    description: "登録内容の変更・修正",
    start: "2026-12-09",
    end: "2026-12-15",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "後期 履修登録取消期間",
    description: "履修の取り消しが可能（最終日は23:55まで）",
    start: "2026-12-19",
    end: "2026-12-25",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "冬季休業期間",
    description: "年末年始の休み",
    start: "2026-12-27",
    end: "2027-01-04",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "月曜日の授業実施",
    description: "成人の日の振替として月曜日の授業を実施",
    start: "2027-01-13",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "学年末試験期間",
    description: "セメスター科目・4Q科目の期末試験",
    start: "2027-02-04",
    end: "2027-02-10",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "4Q 試験",
    description: "第4クウォーター試験日",
    start: "2027-01-28",
    end: "2027-02-18",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "試験予備日",
    description: "非常変災等による試験延期時の予備日",
    start: "2027-02-14",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
  {
    title: "試験予備日",
    description: "非常変災等による試験延期時の予備日",
    start: "2027-02-21",
    link: "https://www.iizuka.kyutech.ac.jp/faculty/educational-info",
  },
];

export default scheduleInfo;
